import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { find, getDirectory } from '../src/node.mjs';

const fixturePath = fileURLToPath(
  new URL('./fixtures/golden_find.tsv', import.meta.url),
);

test('basic lookups', () => {
  assert.equal(find('臺北市'), '1');
  assert.equal(find('臺北市信義區'), '110');
  assert.equal(find('臺北市信義區市府路1號'), '110204');
  assert.equal(find('松山區'), '105');           // road-only, no city/area
  assert.equal(find('台北市秀山街'), '100005');  // "台" -> "臺" normalization
});

test('house-number range rules (odd/even, above/below, between)', () => {
  assert.equal(find('臺北市中山區一江街19號'), '104091');
  assert.equal(find('臺北市中山區一江街21號'), '104092');
  assert.equal(find('臺北市中山區一江街39號'), '104092');
  assert.equal(find('臺北市中山區一江街41號'), '104088');
});

test('differential match against the Python reference implementation', () => {
  // fixtures/golden_find.tsv was generated by running the upstream
  // moskytw/zipcodetw Python package's Directory.find() over ~88k queries
  // stride-sampled across the full 2102_01 dataset, plus manual edge cases.
  const dir = getDirectory();
  const lines = readFileSync(fixturePath, 'utf8').split('\n').filter(Boolean);
  let mismatches = 0;
  for (const line of lines) {
    const tab = line.indexOf('\t');
    const query = line.slice(0, tab);
    const want = line.slice(tab + 1);
    const got = dir.find(query);
    if (got !== want) {
      mismatches++;
      if (mismatches <= 10) {
        console.error(`mismatch: find(${JSON.stringify(query)}) = ${JSON.stringify(got)}, want ${JSON.stringify(want)}`);
      }
    }
  }
  assert.equal(mismatches, 0, `${mismatches}/${lines.length} queries diverged from the Python reference`);
});
