import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { find, getDirectory, lookup } from '../src/node.mjs';
import { Directory, loadDirectory } from '../src/zipcodetw.mjs';

const fixturePath = fileURLToPath(
  new URL('./fixtures/golden_find.tsv', import.meta.url),
);

const publicZipcode = (zipcode) =>
  zipcode.length >= 6 ? zipcode : zipcode.length >= 3 ? zipcode.slice(0, 3) : '';

test('basic lookups', () => {
  assert.equal(find('臺北市'), '');
  assert.equal(find('臺北市信義區'), '110');
  assert.equal(find('臺北市信義區市府路1號'), '110204');
  assert.equal(find('松山區'), '105');           // road-only, no city/area
  assert.equal(find('木柵路'), '116');           // never expose an invalid 4-digit prefix
  assert.equal(find('台北市秀山街'), '100005');  // "台" -> "臺" normalization
});

test('lookup exposes resolution for incomplete addresses', () => {
  assert.deepEqual(lookup('木柵路'), {
    zipcode: '116', source: 'gradual', resolution: 'three-digit',
  });
  assert.deepEqual(lookup('臺北市'), {
    zipcode: '1', source: 'gradual', resolution: 'prefix',
  });
  assert.equal(lookup('不存在的地址'), null);
});

test('browser loader builds a directory and reports failed data requests', async () => {
  const directory = await loadDirectory({
    gradualUrl: '/gradual.tsv',
    preciseUrl: '/precise.tsv',
    fetch: async (url) => ({
      ok: true,
      status: 200,
      text: async () => url === '/gradual.tsv' ? '0\t臺北市\t110' : '',
    }),
  });
  assert.equal(directory.find('臺北市'), '110');

  await assert.rejects(
    loadDirectory({
      gradualUrl: '/missing.tsv',
      preciseUrl: '/precise.tsv',
      fetch: async () => ({ ok: false, status: 404 }),
    }),
    /Could not load postal data from \/missing\.tsv \(HTTP 404\)/,
  );
});

test('house-number range rules (odd/even, above/below, between)', () => {
  assert.equal(find('臺北市中山區一江街19號'), '104091');
  assert.equal(find('臺北市中山區一江街21號'), '104092');
  assert.equal(find('臺北市中山區一江街39號'), '104092');
  assert.equal(find('臺北市中山區一江街41號'), '104088');
});

test('never contradicts the Python reference', () => {
  // fixtures/golden_find.tsv was generated by running the upstream
  // moskytw/zipcodetw Python package's Directory.find() over ~88k queries
  // stride-sampled across the full 2102_01 dataset, plus manual edge cases.
  //
  // canonicalize() resolves addresses the reference leaves coarse, so equality
  // is too strong: we may only refine an answer, never contradict one.
  const dir = getDirectory();
  const lines = readFileSync(fixturePath, 'utf8').split('\n').filter(Boolean);
  let regressions = 0;
  let refinements = 0;
  for (const line of lines) {
    const tab = line.indexOf('\t');
    const query = line.slice(0, tab);
    const want = publicZipcode(line.slice(tab + 1));
    const got = dir.find(query);
    if (got === want) continue;
    if (got.length > want.length && got.startsWith(want)) {
      refinements++;
      continue;
    }
    regressions++;
    if (regressions <= 10) {
      console.error(`regression: find(${JSON.stringify(query)}) = ${JSON.stringify(got)}, want ${JSON.stringify(want)}`);
    }
  }
  assert.equal(regressions, 0, `${regressions}/${lines.length} queries contradict the Python reference`);
  assert.ok(refinements > 0, 'expected the alias index to refine some reference answers');
});

test('the packed store answers identically to the map store', () => {
  // Everything above exercises the Node entry point, which is Map-backed; the
  // browser entry point defaults to the packed tables. Replay the same corpus
  // through both so the binary search cannot drift from the hash lookups.
  const dataPath = (name) => fileURLToPath(new URL(`../data/${name}`, import.meta.url));
  const tsv = {
    gradualTsv: readFileSync(dataPath('gradual.tsv'), 'utf8'),
    preciseTsv: readFileSync(dataPath('precise.tsv'), 'utf8'),
  };
  const mapDir = new Directory({ ...tsv, storage: 'map' });
  const packedDir = new Directory({ ...tsv, storage: 'packed' });

  const lines = readFileSync(fixturePath, 'utf8').split('\n').filter(Boolean);
  let mismatches = 0;
  for (const line of lines) {
    const query = line.slice(0, line.indexOf('\t'));
    const fromMap = mapDir.find(query);
    const fromPacked = packedDir.find(query);
    if (fromMap === fromPacked) continue;
    mismatches++;
    if (mismatches <= 10) {
      console.error(`differ: find(${JSON.stringify(query)}) map=${JSON.stringify(fromMap)} packed=${JSON.stringify(fromPacked)}`);
    }
  }
  assert.equal(mismatches, 0, `${mismatches}/${lines.length} queries differ between storage backends`);

  // aliasIndex() walks every precise key, so the two must enumerate alike.
  const mapKeys = [...mapDir.store.preciseKeys()];
  const packedKeys = [...packedDir.store.preciseKeys()];
  assert.deepEqual(packedKeys, mapKeys);
});

test('resolves addresses that omit the city, the district, or both', () => {
  assert.equal(find('臺北市中山區松江路100號'), '104091');
  assert.equal(find('臺北市松江路100號'), '104091');
  assert.equal(find('中山區松江路100號'), '104091');
  assert.equal(find('松江路100號'), '104091');

  // 中華路二段 spans 中正區 and 萬華區: stay coarse rather than guess, and do
  // not drop 二段 to fall back onto 士林區中華路.
  assert.equal(find('臺北市中華路二段'), '');
});
